#! /bin/sh

bspc config border_width        2
bspc config window_gap         10
bspc config top_padding        15
bspc config split_ratio        0.5

# Theme
bspc config focused_border_color "#B0777B"
bspc config normal_border_color  "#707070"

bspc config split_ratio         0.52
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true

bspc monitor -d I II III IV V VI VII VIII IX X

feh --bg-scale ~/cat7.jpg
